apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CartService
  template:
    metadata:
      labels:
        app: CartService
    spec:
      containers:
      - name: cartrepos
        image: truyumappcr.azurecr.io/cartrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: truyumappsn

---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: CartService